steps:
  - type: transform
    name: "1_transform"
    registry_path: "config/1_transform_registry.yaml"
    report_path: "transform_reports"
    input_folder_path: "input"
    output_folder_path: null  

  - type: validate
    name: "2_validation"
    registry_path: "config/2_validation_registry.yaml"
    report_path: "validation_reports"
    input_folder_path: "1_transform"
    output_folder_path: "delivery"  

  - type: custom_step
    name: "3_custom"
    registry_path: "config/3_custom_registry.yaml"
    report_path: "custom_reports"
    input_folder_path: "delivery"
    output_folder_path: "final_output"
    custom_param: "example_value"  # Custom parameter for this step
